name: Portfolio Web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Change directory to your portfolio app
            cd /home/deploy/Portfolio

            git pull origin main

            docker build -t portfolio .

            docker stop portfolio || true
            docker rm portfolio || true

            docker run -d -p 3001:3000 --name portfolio portfolio

